version: '3.8'
services:
  frontend:
    build:
      context: ./HCI_project
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    ports:
      - "8081:80"
    environment:
      - NODE_ENV=development
    depends_on:
      - auth-service
      - product-service
      - notification-service
      - wishlist-service
      - chat-service

  auth-service:
    build: ./services/auth-service
    ports:
      - "4140:4000"
    env_file:
      - ./services/auth-service/.env
    depends_on:
      - mongodb

  product-service:
    build: ./services/product-service
    ports:
      - "4141:4001"
    env_file:
      - ./services/product-service/.env
    depends_on:
      - mongodb

  notification-service:
    build: ./services/notification-service
    ports:
      - "4142:4002"
    env_file:
      - ./services/notification-service/.env
    depends_on:
      - mongodb

  wishlist-service:
    build: ./services/wishlist-service
    ports:
      - "4143:4003"
    env_file:
      - ./services/wishlist-service/.env
    depends_on:
      - mongodb

  chat-service:
    build: ./services/chat-service
    ports:
      - "4144:4004"
    env_file:
      - ./services/chat-service/.env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 