version: '3.8'
services:
  frontend:
    build:
      context: ./HCI_project
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    ports:
      - "8083:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - auth-service
      - product-service
      - notification-service
      - wishlist-service
      - chat-service

  auth-service:
    build: ./services/auth-service
    ports:
      - "4130:4000"
    env_file:
      - ./services/auth-service/.env

  product-service:
    build: ./services/product-service
    ports:
      - "4131:4001"
    env_file:
      - ./services/product-service/.env

  notification-service:
    build: ./services/notification-service
    ports:
      - "4132:4002"
    env_file:
      - ./services/notification-service/.env

  wishlist-service:
    build: ./services/wishlist-service
    ports:
      - "4133:4003"
    env_file:
      - ./services/wishlist-service/.env

  chat-service:
    build: ./services/chat-service
    ports:
      - "4134:4004"
    env_file:
      - ./services/chat-service/.env

networks:
  app-network:
    driver: bridge