apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
      - name: chat-service
        image: cloudproject-chat-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4004
        env:
        - name: MONGODB_URI
          value: "mongodb+srv://khalil:ukzwimpcv8mzCYpt@cluster0.gje5dvf.mongodb.net/chat"
        
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  selector:
    app: chat-service
  ports:
    - protocol: TCP
      port: 4004
      targetPort: 4004
      nodePort: 31238
  type: NodePort
