apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: cloudproject-notification-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4002
        env:
        - name: MONGODB_URI
          value: "mongodb+srv://khalil:ukzwimpcv8mzCYpt@cluster0.gje5dvf.mongodb.net/notification"
        
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 4002
      targetPort: 4002
      nodePort: 31236
  type: NodePort
