apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: cloudproject-product-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4001
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: product-mongodb-uri-secret
              key: MONGODB_URI
        
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
      nodePort: 31235
  type: NodePort
